spring.application.name=cloudcart-api

spring.datasource.url=jdbc:h2:mem:cloudcart

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.h2.console.enabled=true

spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev

jwt.secret=Q2xvdWRDYXJ0U3VwZXJTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY3ODkw
jwt.expiration=86400000

# Your application logs
logging.level.com.cloudcart=INFO

## Disable Spring Boot logs
#logging.level.org.springframework=OFF
#logging.level.org.springframework.boot=OFF
#
## Disable Hibernate (if using JPA)
#logging.level.org.hibernate=OFF
#
## Disable Tomcat
#logging.level.org.apache.catalina=OFF
#logging.level.org.apache.coyote=OFF
#
## Disable HikariCP
#logging.level.com.zaxxer.hikari=OFF